// In your Topics.js or a separate file
const keywords = {
  software: [
    "code",
    "development",
    "programming",
    "technology",
    "coding",
    "software engineering",
    "web development",
    "app development",
    "coding languages",
    "software tools",
    "debugging",
    "version control",
    "agile",
    "scrum",
    "developer",
    "frontend",
    "backend",
    "API",
    "database",
    "algorithm",
    "data structure",
    "framework",
    "library",
    "testing",
    "automation",
    "deployment",
    "CI/CD",
    "security",
    "software architecture",
    "mobile development",
    "UI/UX",
    "responsive design",
    "software project",
    "software documentation",
    "code review",
    "code quality",
    "software team",
    "open source",
    "developer community",
    "software trends",
    "software industry",
    "software updates",
    "code efficiency",
    "software performance",
    "software optimization",
    "software maintenance",
    "software best practices",
    "software design patterns",
    "refactoring",
    "code readability",
    "software scalability",
    "software reliability",
    "software usability",
    "software collaboration",
    "coding tips",
    "programming challenges",
    "programming languages comparison",
    "software success stories",
    "tech stack",
    "code review tips",
    "developer tools",
    "software workflow",
    "developer productivity",
    "continuous learning in software",
    "software innovation",
    "software solutions",
    "emerging technologies",
    "software conferences",
    "software resources",
    "software documentation tips",
    "software community",
    "code efficiency tips",
    "software performance optimization",
    "software maintenance strategies",
    "software best practices guide",
    "coding tips and tricks",
    "programming challenges solutions",
    "software success stories overview",
    "tech stack overview",
    "code review tips overview",
    "developer tools overview",
    "software workflow overview",
    "developer productivity overview",
    "continuous learning in software overview",
    "software innovation overview",
    "software solutions overview",
    "emerging technologies overview",
    "software conferences overview",
    "software resources overview",
    "software documentation tips overview",
    "software community overview",
    "code efficiency tips overview",
    "software performance optimization overview",
    "software maintenance strategies overview",
    "software best practices guide overview",
    "coding tips and tricks overview",
  ],
  career: [
    "career",
    "job",
    "employment",
    "profession",
    "work",
    "interview",
    "resume",
    "skills",
    "networking",
    "job search",
    "professional development",
    "workplace",
    "job market",
    "career growth",
    "career transition",
    "career path",
    "job interview",
    "career advice",
    "job hunting",
    "job application",
    "career change",
    "career planning",
    "job satisfaction",
    "career goals",
    "job opportunities",
    "job satisfaction",
    "job offer",
    "job application process",
    "job seeking",
    "employment opportunities",
    "job prospects",
    "career advancement",
    "job application tips",
    "job interview tips",
    "career success",
    "career exploration",
    "job search strategies",
    "career choices",
    "job seeking tips",
    "career development",
    "job market trends",
    "career coaching",
    "job search techniques",
    "career building",
    "job search resources",
    "employment trends",
    "job market analysis",
    "career exploration tools",
    "job application techniques",
    "job search advice",
    "career planning strategies",
    "job market insights",
    "career advice articles",
    "job hunting strategies",
    "career growth tips",
    "job search insights",
    "employment trends analysis",
    "career change advice",
    "job interview preparation",
    "career path choices",
    "job satisfaction factors",
    "career goals setting",
    "job opportunities research",
    "job satisfaction factors",
    "job offer negotiation",
    "job application writing",
    "career success stories",
    "career exploration journey",
    "job search success stories",
    "career choices guide",
    "job seeking success",
    "career development resources",
    "job market trends analysis",
    "career coaching insights",
    "job search techniques guide",
    "career building tips",
    "job search resources list",
    "employment trends overview",
    "job market analysis report",
    "career exploration tools review",
    "job application techniques insights",
    "job search advice articles",
    "career planning strategies overview",
    "job market insights overview",
    "career advice articles review",
    "job hunting strategies overview",
    "career growth tips overview",
    "job search insights overview",
    "employment trends analysis report",
    "career change advice overview",
    "job interview preparation insights",
    "career path choices overview",
    "job satisfaction factors overview",
    "career goals setting overview",
    "job opportunities research insights",
    "job satisfaction factors overview",
    "job offer negotiation insights",
    "job application writing tips",
    "career success stories overview",
    "career exploration journey overview",
    "job search success stories overview",
    "career choices guide overview",
    "job seeking success overview",
    "career development resources overview",
    "job market trends analysis overview",
    "career coaching insights overview",
    "job search techniques guide overview",
    "career building tips overview",
    "job search resources list overview",
    "employment trends overview overview",
    "job market analysis report overview",
    "career exploration tools review overview",
    "job application techniques insights overview",
    "job search advice articles overview",
    "career planning strategies overview overview",
    "job market insights overview overview",
    "career advice articles review overview",
    "job hunting strategies overview overview",
    "career growth tips overview overview",
    "job search insights overview overview",
    "employment trends analysis report overview",
    "career change advice overview overview",
    "job interview preparation insights overview",
    "career path choices overview overview",
    "job satisfaction factors overview overview",
    "career goals setting overview overview",
    "job opportunities research insights overview",
    "job satisfaction factors overview overview",
    "job offer negotiation insights overview",
    "job application writing tips overview",
    "career success stories overview overview",
    "career exploration journey overview overview",
    "job search success stories overview overview",
    "career choices guide overview overview",
    "job seeking success overview overview",
    "career development resources overview overview",
    "job market trends analysis overview overview",
    "career coaching insights overview overview",
    "job search techniques guide overview overview",
    "career building tips overview overview",
    "job search resources list overview overview",
    "employment trends overview overview",
    "job market analysis report overview overview",
    "career exploration tools review overview overview",
    "job application techniques insights overview overview",
    "job search advice articles overview overview",
    "career planning strategies overview overview overview",
  ],

  product: [
    "product",
    "product management",
    "product development",
    "product design",
    "product strategy",
    "product roadmap",
    "product lifecycle",
    "product launch",
    "product market fit",
    "product owner",
    "product backlog",
    "product features",
    "product iteration",
    "product prototype",
    "user experience",
    "user feedback",
    "market research",
    "customer needs",
    "user stories",
    "minimum viable product",
    "product success",
    "product failure",
    "product iteration",
    "product scalability",
    "product testing",
    "product release",
    "product innovation",
    "product improvement",
    "product planning",
    "product analytics",
    "product metrics",
    "product value",
    "product vision",
    "product branding",
    "product positioning",
    "product differentiation",
    "product collaboration",
    "product team",
    "product success stories",
    "product development process",
    "product design thinking",
    "product problem-solving",
    "product user personas",
    "product feedback loop",
    "product communication",
    "product collaboration tools",
    "product design iteration",
    "product management tool",
    "product development tool",
    "product roadmap planning",
    "product launch strategy",
    "product market research",
    "customer needs analysis",
    "user stories creation",
    "minimum viable product planning",
    "product success analysis",
    "product failure analysis",
    "product scalability planning",
    "product testing strategy",
    "product release planning",
    "product innovation process",
    "product improvement planning",
    "product planning strategies",
    "product analytics tools",
    "product metrics tracking",
    "product value analysis",
    "product vision creation",
    "product branding strategy",
    "product positioning tactics",
    "product differentiation techniques",
    "product collaboration methods",
    "product team collaboration",
    "product success stories analysis",
    "product development process overview",
    "product design thinking principles",
    "product problem-solving strategies",
    "product user personas creation",
    "product feedback loop implementation",
    "product communication strategies",
    "product collaboration tools overview",
    "product design iteration process",
    "product management tool overview",
    "product development tool overview",
    "product roadmap planning overview",
    "product launch strategy overview",
    "product market research overview",
    "customer needs analysis overview",
    "user stories creation overview",
    "minimum viable product planning overview",
    "product success analysis overview",
    "product failure analysis overview",
    "product scalability planning overview",
    "product testing strategy overview",
    "product release planning overview",
    "product innovation process overview",
    "product improvement planning overview",
    "product planning strategies overview",
    "product analytics tools overview",
    "product metrics tracking overview",
    "product value analysis overview",
    "product vision creation overview",
    "product branding strategy overview",
    "product positioning tactics overview",
    "product differentiation techniques overview",
    "product collaboration methods overview",
    "product team collaboration overview",
    "product success stories analysis overview",
  ],
  internships: [
    "internship",
    "intern",
    "internship experience",
    "internship application",
    "internship opportunity",
    "internship process",
    "internship benefits",
    "internship challenges",
    "internship skills",
    "internship tips",
    "internship resume",
    "internship interview",
    "internship success stories",
    "internship advice",
    "internship networking",
    "internship learning",
    "internship company",
    "internship role",
    "internship responsibilities",
    "internship tasks",
    "internship collaboration",
    "internship projects",
    "internship mentorship",
    "internship growth",
    "internship feedback",
    "internship goals",
    "internship achievements",
    "internship reflections",
    "internship lessons learned",
    "internship career development",
    "internship skill development",
    "internship project management",
    "internship communication",
    "internship teamwork",
    "internship challenges overcoming",
    "internship success factors",
    "internship preparation",
    "internship learning curve",
    "internship adaptation",
    "internship feedback incorporation",
    "internship goal achievement",
    "internship achievements celebration",
    "internship reflections review",
    "internship lessons learned documentation",
    "internship career development plan",
    "internship skill development strategies",
    "internship project management tactics",
    "internship communication improvement",
    "internship teamwork enhancement",
    "internship challenges overcoming strategies",
    "internship success factors analysis",
    "internship preparation strategies",
    "internship learning curve insights",
    "internship adaptation strategies",
    "internship feedback incorporation overview",
    "internship goal achievement overview",
    "internship achievements celebration overview",
    "internship reflections review overview",
    "internship lessons learned documentation overview",
    "internship career development plan overview",
    "internship skill development strategies overview",
    "internship project management tactics overview",
    "internship communication improvement overview",
    "internship teamwork enhancement overview",
    "internship challenges overcoming strategies overview",
    "internship success factors analysis overview",
    "internship preparation strategies overview",
  ],
  college: [
    "code",
    "college",
    "university",
    "education",
    "academic",
    "campus",
    "student life",
    "college experience",
    "college courses",
    "college major",
    "college minor",
    "college projects",
    "college exams",
    "college grades",
    "college success",
    "college challenges",
    "college tips",
    "college application",
    "college admission",
    "college social life",
    "college extracurriculars",
    "college networking",
    "college resources",
    "college support",
    "college community",
    "college clubs",
    "college events",
    "college diversity",
    "college inclusion",
    "college learning",
    "college growth",
    "college achievements",
    "college goals",
    "college reflection",
    "college lessons learned",
    "college academic journey",
    "college social journey",
    "college networking insights",
    "college resources utilization",
    "college support appreciation",
    "college community engagement",
    "college clubs involvement",
    "college events participation",
    "college diversity celebration",
    "college inclusion acknowledgment",
    "college learning experiences",
    "college growth experiences",
    "college achievements recognition",
    "college goals setting",
    "college reflection documentation",
    "college lessons learned documentation",
    "college academic journey overview",
    "college social journey overview",
    "college networking insights overview",
    "college resources utilization overview",
    "college support appreciation overview",
    "college community engagement overview",
    "college clubs involvement overview",
    "college events participation overview",
    "college diversity celebration overview",
    "college inclusion acknowledgment overview",
    "college learning experiences overview",
    "college growth experiences overview",
    "college achievements recognition overview",
    "college goals setting overview",
    "college reflection documentation overview",
    "college lessons learned documentation overview",
  ],
  experiences: [
    "experiences",
    "life experiences",
    "personal growth",
    "lessons learned",
    "life reflections",
    "self-discovery",
    "personal development",
    "challenges faced",
    "overcoming obstacles",
    "success stories",
    "achievements",
    "goal setting",
    "adventures",
    "travel experiences",
    "cultural experiences",
    "life lessons",
    "mindset shift",
    "positive mindset",
    "gratitude",
    "self-improvement",
    "emotional intelligence",
    "leadership experiences",
    "communication skills",
    "interpersonal skills",
    "relationships",
    "friendship experiences",
    "family experiences",
    "career experiences",
    "workplace experiences",
    "professional growth",
    "career challenges",
    "workplace success",
    "workplace relationships",
    "workplace communication",
    "workplace collaboration",
    "workplace leadership",
    "workplace productivity",
    "workplace balance",
    "work-life balance",
    "time management",
    "stress management",
    "self-care",
    "mental health",
    "physical health",
    "healthy habits",
    "well-being",
    "hobbies",
    "passions",
    "creative experiences",
    "artistic experiences",
    "music experiences",
    "sports experiences",
    "fitness experiences",
    "learning experiences",
    "educational experiences",
    "technology experiences",
    "innovation experiences",
    "entrepreneurial experiences",
    "startup experiences",
    "business experiences",
    "success strategies",
    "failure experiences",
    "resilience",
    "persistence",
    "mindfulness",
    "reflection",
    "continuous learning",
    "adaptability",
    "flexibility",
    "open-mindedness",
    "curiosity",
    "exploration",
    "adventure seeking",
    "self-expression",
    "personal achievements",
    "personal goals",
    "personal growth journey",
    "life experiences overview",
    "personal growth overview",
    "lessons learned overview",
    "life reflections overview",
    "self-discovery overview",
    "personal development overview",
    "challenges faced overview",
    "overcoming obstacles overview",
    "success stories overview",
    "achievements overview",
    "goal setting overview",
    "adventures overview",
    "travel experiences overview",
    "cultural experiences overview",
    "life lessons overview",
    "mindset shift overview",
    "positive mindset overview",
    "gratitude overview",
    "self-improvement overview",
    "emotional intelligence overview",
    "leadership experiences overview",
    "communication skills overview",
    "interpersonal skills overview",
    "relationships overview",
    "friendship experiences overview",
    "family experiences overview",
    "career experiences overview",
    "workplace experiences overview",
    "professional growth overview",
    "career challenges overview",
    "workplace success overview",
    "workplace relationships overview",
    "workplace communication overview",
    "workplace collaboration overview",
    "workplace leadership overview",
    "workplace productivity overview",
    "workplace balance overview",
    "work-life balance overview",
    "time management overview",
    "stress management overview",
    "self-care overview",
    "mental health overview",
    "physical health overview",
    "healthy habits overview",
    "well-being overview",
    "hobbies overview",
    "passions overview",
    "creative experiences overview",
    "artistic experiences overview",
  ],

  machinelearning: [
    'ML',
    "Neural Networks",
    "Deep Learning",
    "Convolutional Neural Networks",
    "Recurrent Neural Networks",
    "Supervised Learning",
    "Unsupervised Learning",
    "Reinforcement Learning",
    "Machine Learning",
    "Classification",
    "Regression",
    "Clustering",
    "Anomaly detection",
    "Natural Language Processing",
    "Computer Vision",
    "Predictive analytics",
    "Data mining",
    "Data preprocessing",
    "Model training",
    "Model optimization",
    "Feature extraction",
    "Feature selection",
    "Overfitting",
    "Underfitting",
    "Support Vector Machines",
    "Decision Trees",
    "Random Forests",
    "Gradient Boosting",
    "K-nearest neighbors",
    "Naive Bayes",
    "Linear regression",
    "Logistic regression",
    "Artificial intelligence",
    "Perceptron",
    "Backpropagation",
    "Gradient descent",
    "Optimization",
    "Loss function",
    "Hyperparameter tuning",
    "Generalization",
    "Validation",
    "Development set",
    "Test set",
    "Precision",
    "Recall",
    "F1 Score",
    "Accuracy",
    "AUC",
    "ROC Curve",
    "Confusion Matrix",
    "Bias",
    "Variance",
    "Bagging",
    "Boosting",
    "Stacking",
    "Transfer Learning",
    "LifeLong Learning",
    "Reinforcement Learning",
    "Q-Learning",
    "Deep Q Network",
    "Experience Replay",
    "Policy Gradients",
    "Imitation Learning",
    "Generative Adversarial Networks",
    "Autoencoders",
    "Word Embeddings",
    "GloVe",
    "word2vec",
    "Dimensionality Reduction",
    "Principal Component Analysis",
    "Singular Value ",
    "BERT",
    "GPT",
    "DNN",
    "CNN",
    "RNN",
    "LSTM",
    "GRU",
    "ImageNet",
    "COCO",
    "MNIST",
    "Kaggle",
    "Private AI",
    "Federated Learning",
    "Edge AI",
    "Explainability",
    "Causality",
    "Trustworthiness",
    "Fairness",
    "Data Privacy",
    "Regex",
    "Pandas",
    "Numpy",
    "Matplotlib",
    "Seaborn",
    "Scikit-learn",
    "Pytorch",
    "Tensorflow",
  ],
  startup: [
    "startup",
    "entrepreneurship",
    "business",
    "business idea",
    "business model",
    "business plan",
    "business strategy",
    "business development",
    "business growth",
    "business success",
    "business failure",
    "business challenges",
    "business opportunities",
    "business innovation",
    "business trends",
    "business market",
    "business competition",
    "business marketing",
    "business branding",
    "business positioning",
    "business differentiation",
    "business collaboration",
    "business team",
    "business success stories",
    "business development process",
    "business strategy planning",
    "business growth strategies",
    "business success factors",
    "business failure analysis",
    "business challenges overcoming",
    "business opportunities research",
    "business innovation process",
    "business trends analysis",
    "business market research",
    "business competition analysis",
    "business marketing strategies",
    "business branding strategy",
    "business positioning tactics",
    "business differentiation techniques",
    "business collaboration methods",
    "business team collaboration",
    "business success stories analysis",
    "business development process overview",
    "business strategy planning overview",
    "business growth strategies overview",
    "business success factors analysis overview",
    "business failure analysis overview",
    "business challenges overcoming strategies overview",
    "business opportunities research insights",
    "business innovation process overview",
    "business trends analysis overview",
    "business market research overview",
    "business competition analysis overview",
    "business marketing strategies overview",
    "business branding strategy overview",
    "business positioning tactics overview",
    "business differentiation techniques overview",
    "business collaboration methods overview",
    "business team collaboration overview",
    "business success stories analysis overview",
  ],
  tech: [
      'Tech',
      'Code',
      'Data',
      'Web',
      'App',
      'API',
      'Byte',
      'Cloud',
      'Java',
      'Node',
      'Ruby',
      'Swift',
      'CSS',
      'HTML',
      'UI',
      'UX',
      'Java',
      'Python',
      'AI',
      'IoT',
      'VR',
      'AR',
      'VPN',
      'Cyber',
      'Hack',
      'Pixel',
      'Bit',
      'Git',
      'Repo',
      'Bug',
      'Beta',
      'Pixel',
      'GIF',
      'URL',
      'Link',
      'SaaS',
      'PaaS',
      'FaaS',
      'API',
      'SDK',
      'NPM',
      'IDE',
      'CLI',
      'CMS',
      'SEO',
      'SEM',
      'LAN',
      'WAN',
      'VPN',
      'HTML5',
      'CSS3',
      'JS',
      'React',
      'Vue',
      'Angular',
      'Node',
      'REST',
      'JSON',
      'XML',
      'HTTPS',
      'SSL',
      'TLS',
      'CLI',
      'SQL',
      'NoSQL',
      'DB',
      'FTP',
      'SSH',
      'SSL',
      'CMS',
      'SEO',
      'SEM',
      'ISP',
      'API',
      'MVP',
      'KPI',
      'Agile',
      'Scrum',
      'Kanban',
      'Git',
      'Repo',
      'Bug',
      'Agile',
      'Scrum',
      'Kanban',
      'DNS',
      'CDN',
      'SDK',
      'CLI',
      'IDE',
      'HTML5',
      'CSS3',
      'JS',
      'SEO',
      'SEM',
      'CRM',
      'ERP',
      'VPN',
      'Agile',
      'Scrum',
      'Kanban',
      'Sprint',
      'API',
      'VR',
      'AR',
      'CMS',
      'DNS',
      'CDN',
      'SaaS'
    
  ],
  ai: [
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Neural Networks",
    "Algorithm",
    "Data Science",
    "Big Data",
    "Automation",
    "Robotics",
    "Natural Language Processing",
    "Computer Vision",
    "Chatbot",
    "Speech Recognition",
    "Predictive Analytics",
    "Cognitive Computing",
    "Expert System",
    "Virtual Assistant",
    "Pattern Recognition",
    "Supervised Learning",
    "Unsupervised Learning",
    "Reinforcement Learning",
    "Data Mining",
    "Knowledge Graph",
    "Algorithmic Decision Making",
    "Algorithmic Bias",
    "Computer Intelligence",
    "Digital Assistant",
    "Autonomous Systems",
    "Quantum Computing",
    "Ethical AI",
    "Explainable AI",
    "AI Ethics",
    "Bias in AI",
    "Machine Translation",
    "Facial Recognition",
    "Image Recognition",
    "Semantic Analysis",
    "Swarm Intelligence",
    "Human-Machine Collaboration",
    "Augmented Intelligence",
    "AI Research",
    "AI Lab",
    "AI Startup",
    "Neuroinformatics",
    "Synthetic Data",
    "Genetic Algorithms",
    "Evolutionary Computing",
    "Fuzzy Logic",
    "Smart Contracts",
    "Internet of Things (IoT)",
    "Edge Computing",
    "Cloud Computing",
    "Data Augmentation",
    "Transfer Learning",
    "Robotic Process Automation",
    "Knowledge Representation",
    "Heuristic Methods",
    "Predictive Modeling",
    "Quantified Self",
    "Humanoid Robot",
    "Expert System",
    "Decision Trees",
    "Cybernetics",
    "Digital Twin",
    "Human-Computer Interaction",
    "Exoskeleton",
    "AI Chip",
    "Bias Mitigation",
    "Neuro-Linguistic Programming",
    "Siri",
    "Alexa",
    "Google Assistant",
    "IBM Watson",
    "Microsoft Azure AI",
    "Machine Vision",
    "Algorithmic Trading",
    "ChatGPT",
    "AI Governance",
    "AIOps",
    "Edge AI",
    "Explainability",
    "Deep Reinforcement Learning",
    "AI in Healthcare",
    "AI in Finance",
    "AI in Education",
    "AI in Marketing",
    "AI in Agriculture",
    "AI in Retail",
    "AI in Transportation",
    "AI in Cybersecurity",
    "AI in Gaming",
    "AI in Robotics",
    "AI in Energy",
    "AI in Entertainment",
    "AI in Space Exploration",
  ],
};

const topicKeywords = {};

for (const topic in keywords) {
  keywords[topic].forEach((keyword) => {
    topicKeywords[keyword.toLowerCase()] = topic;
  });
}

export { topicKeywords, keywords };
