version: '3'

services:
  prod:
    build: 
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - '4173:4173'
    environment:
      - NODE_ENV=production

  dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
